name: ci tag browsers
on: [push]
jobs:
  tests-all-chrome:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run (Chrome)
        uses: cypress-io/github-action@v4
        with:
          # check the spec types
          build: npm run lint
          # start the application before running Cypress
          start: npm run start-quiet
          browser: chrome

  tests-sanity-firefox:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run (Firefox)
        uses: cypress-io/github-action@v4
        with:
          # check the spec types
          build: npm run lint
          # start the application before running Cypress
          start: npm run start-quiet
          browser: firefox
          # cy.dblclick did not work in headless FF mode
          headed: true
          env: grepTags=@sanity

  tests-sanity-plus-webkit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Install dependencies
        uses: cypress-io/github-action@v4
        with:
          # install WebKit browser dependencies
          build: npx playwright install-deps webkit
          runTests: false

      - name: Cypress run (WebKit)
        uses: cypress-io/github-action@v4
        with:
          # we have already installed everything
          install: false
          # check the spec types
          build: npm run lint
          # start the application before running Cypress
          start: npm run start-quiet
          browser: webkit
          env: grepTags='@sanity @webkit'
